const LOCATIONS = [
  "Space rocket", "Space station", "Bank", "Office", "Conference room",
  "Reception area", "Call center", "Data center", "Laboratory", "Television studio",
  "Radio station", "Recycling plant", "Power substation", "Mine", "Home",
  "Backyard", "Balcony", "Garden", "Garage", "Kitchen",
  "Bedroom", "Attic", "Farmhouse", "Treehouse", "Eiffel Tower (France)",
  "Colosseum (Italy)", "Big Ben (UK)", "Statue of Liberty (USA)", "Great Wall of China (China)", "Mount Fuji (Japan)",
  "Burj Khalifa (UAE)", "Times Square (USA)", "Red Square (Russia)", "Grand Canyon (USA)", "Temple",
  "Church", "Monastery", "Park", "Forest", "Lake",
  "Waterfall", "Beach", "Mountain", "Desert", "Cave",
  "Volcano", "Botanical garden", "Zoo", "Aquarium", "Picnic area",
  "Supermarket", "Butcher shop", "Bakery", "Flower shop", "Barber shop",
  "Beauty salon", "Shopping mall", "Post office", "Dry cleaner", "Car wash",
  "Gas station", "Hotel", "Restaurant", "Café", "Bar",
  "Nightclub", "Casino", "Bookstore", "Electronics store", "Pet shop",
  "Hospital", "Pharmacy", "Dentist", "Veterinary clinic", "Fire station",
  "Police station", "Nursing home", "School", "Kindergarten", "University campus",
  "Playground", "Library", "Art gallery", "Museum", "Theater",
  "Gym", "Swimming pool", "Stadium", "Music school", "Dance studio",
  "Driving school", "Planetarium", "Bus stop", "Metro station", "Train station",
  "Airport", "Parking lot", "City square", "Skyscraper", "Bridge",
  "Fountain", "Public restroom", "Factory", "Office building", "Embassy",
  "Courthouse", "Paris", "Tokyo", "New York", "London",
  "Rome", "Hawaii", "Ski resort", "Village", "Bowling",
  "Tennis court",
];

export const RU_LOCATION_MAP = {
  "Space rocket": "Ракета",
  "Space station": "Космическая станция",
  "Bank": "Банк",
  "Office": "Офис",
  "Conference room": "Конференц-зал",
  "Reception area": "Ресепшен",
  "Call center": "Колл-центр",
  "Data center": "Дата-центр",
  "Laboratory": "Лаборатория",
  "Television studio": "Телестудия",
  "Radio station": "Радиостанция",
  "Recycling plant": "Завод по переработке",
  "Power substation": "Электроподстанция",
  "Mine": "Шахта",
  "Home": "Дом",
  "Backyard": "Задний двор",
  "Balcony": "Балкон",
  "Garden": "Сад",
  "Garage": "Гараж",
  "Kitchen": "Кухня",
  "Bedroom": "Спальня",
  "Attic": "Чердак",
  "Farmhouse": "Ферма",
  "Treehouse": "Домик на дереве",
  "Eiffel Tower (France)": "Эйфелева башня (Франция)",
  "Colosseum (Italy)": "Колизей (Италия)",
  "Big Ben (UK)": "Биг-Бен (Великобритания)",
  "Statue of Liberty (USA)": "Статуя Свободы (США)",
  "Great Wall of China (China)": "Великая китайская стена (Китай)",
  "Mount Fuji (Japan)": "Гора Фудзи (Япония)",
  "Burj Khalifa (UAE)": "Бурдж-Халифа (ОАЭ)",
  "Times Square (USA)": "Таймс-сквер (США)",
  "Red Square (Russia)": "Красная площадь (Россия)",
  "Grand Canyon (USA)": "Гранд-Каньон (США)",
  "Temple": "Храм",
  "Church": "Церковь",
  "Monastery": "Монастырь",
  "Park": "Парк",
  "Forest": "Лес",
  "Lake": "Озеро",
  "Waterfall": "Водопад",
  "Beach": "Пляж",
  "Mountain": "Гора",
  "Desert": "Пустыня",
  "Cave": "Пещера",
  "Volcano": "Вулкан",
  "Botanical garden": "Ботанический сад",
  "Zoo": "Зоопарк",
  "Aquarium": "Аквариум",
  "Picnic area": "Пикник",
  "Supermarket": "Супермаркет",
  "Butcher shop": "Мясная лавка",
  "Bakery": "Пекарня",
  "Flower shop": "Цветочный магазин",
  "Barber shop": "Парикмахерская",
  "Beauty salon": "Салон красоты",
  "Shopping mall": "Торговый центр",
  "Post office": "Почта",
  "Dry cleaner": "Химчистка",
  "Car wash": "Автомойка",
  "Gas station": "Авто-заправочная станция",
  "Hotel": "Отель",
  "Restaurant": "Ресторан",
  "Café": "Кафе",
  "Bar": "Бар",
  "Nightclub": "Ночной клуб",
  "Casino": "Казино",
  "Bookstore": "Книжный магазин",
  "Electronics store": "Магазин электроники",
  "Pet shop": "Зоомагазин",
  "Hospital": "Больница",
  "Pharmacy": "Аптека",
  "Dentist": "Кабинет стоматолога",
  "Veterinary clinic": "Ветеринарная клиника",
  "Fire station": "Пожарная станция",
  "Police station": "Полицейский участок",
  "Nursing home": "Дом престарелых",
  "School": "Школа",
  "Kindergarten": "Детский сад",
  "University campus": "Университет",
  "Playground": "Детская площадка",
  "Library": "Библиотека",
  "Art gallery": "Художественная галерея",
  "Museum": "Музей",
  "Theater": "Театр",
  "Gym": "Спортзал",
  "Swimming pool": "Бассейн",
  "Stadium": "Стадион",
  "Music school": "Музыкальная школа",
  "Dance studio": "Танцевальная студия",
  "Driving school": "Автошкола",
  "Planetarium": "Планетарий",
  "Bus stop": "Автобусная остановка",
  "Metro station": "Станция метро",
  "Train station": "Железнодорожный вокзал",
  "Airport": "Аэропорт",
  "Parking lot": "Парковка",
  "City square": "Городская площадь",
  "Skyscraper": "Небоскрёб",
  "Bridge": "Мост",
  "Fountain": "Фонтан",
  "Public restroom": "Общественный туалет",
  "Factory": "Фабрика",
  "Office building": "Офисное здание",
  "Embassy": "Посольство",
  "Courthouse": "Суд",
  "Paris": "Париж",
  "Tokyo": "Токио",
  "New York": "Нью-Йорк",
  "London": "Лондон",
  "Rome": "Рим",
  "Hawaii": "Гавайи",
  "Hawai": "Гавайи",
  "Ski resort": "Горнолыжный курорт",
  "Village": "Деревня",
  "Bowling": "Боулинг",
  "Tennis court": "Теннисный корт",
};

export function translateLocation(location, language) {
  if (language === "ru") {
    return RU_LOCATION_MAP[location] || location;
  }
  return location;
}

export default LOCATIONS;